version: '3.8'

services:

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: deep
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Employee
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: deep
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8080:8080"
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: Employee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: deep
    ports:
      - "5432:5432"
